/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addEvent.java
 *
 * Created on Sep 27, 2009, 8:18:19 PM
 */

package telecal;

/**
 *
 * @author thibault
 */
public class addEditContact extends javax.swing.JFrame {

    /** Creates new form addEvent */
    public addEditContact() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                contactNameLabel = new java.awt.Label();
                contactNameText = new java.awt.TextField();
                cellPhoneNumberLabel = new java.awt.Label();
                cellPhoneNumberText = new java.awt.TextField();
                emailAdressLabel = new java.awt.Label();
                acceptBtn = new java.awt.Button();
                cancelBtn = new java.awt.Button();
                adressLabel = new java.awt.Label();
                emailAdressText = new java.awt.TextField();
                addressText1 = new java.awt.TextField();
                kindOfContactText = new java.awt.TextField();
                kindOfContactLabel = new java.awt.Label();
                groupLabel = new java.awt.Label();
                groupComboBox = new javax.swing.JComboBox();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setName("Form"); // NOI18N

                contactNameLabel.setName("contactNameLabel"); // NOI18N
                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(telecal.TeleCalApp.class).getContext().getResourceMap(addEditContact.class);
                contactNameLabel.setText(resourceMap.getString("contactNameLabel.text")); // NOI18N

                contactNameText.setName("contactNameText"); // NOI18N
                contactNameText.setText(resourceMap.getString("contactNameText.text")); // NOI18N

                cellPhoneNumberLabel.setName("cellPhoneNumberLabel"); // NOI18N
                cellPhoneNumberLabel.setText(resourceMap.getString("cellPhoneNumberLabel.text")); // NOI18N

                cellPhoneNumberText.setName("cellPhoneNumberText"); // NOI18N
                cellPhoneNumberText.setText(resourceMap.getString("cellPhoneNumberText.text")); // NOI18N

                emailAdressLabel.setName("emailLabel"); // NOI18N
                emailAdressLabel.setText(resourceMap.getString("emailLabel.text")); // NOI18N

                acceptBtn.setLabel(resourceMap.getString("Accept.label")); // NOI18N
                acceptBtn.setName("Accept"); // NOI18N

                cancelBtn.setLabel(resourceMap.getString("cancelBtn.label")); // NOI18N
                cancelBtn.setName("cancelBtn"); // NOI18N
                cancelBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelBtnActionPerformed(evt);
                        }
                });

                adressLabel.setName("adressLabel"); // NOI18N
                adressLabel.setText(resourceMap.getString("adressLabel.text")); // NOI18N

                emailAdressText.setName("emailAddressText"); // NOI18N
                emailAdressText.setText(resourceMap.getString("emailAddressText.text")); // NOI18N

                addressText1.setName("addressText"); // NOI18N
                addressText1.setText(resourceMap.getString("addressText.text")); // NOI18N

                kindOfContactText.setName("kindOfContactText"); // NOI18N
                kindOfContactText.setText(resourceMap.getString("kindOfContactText.text")); // NOI18N

                kindOfContactLabel.setName("kindOfContactLabel"); // NOI18N
                kindOfContactLabel.setText(resourceMap.getString("kindOfContactLabel.text")); // NOI18N

                groupLabel.setName("groupLabel"); // NOI18N
                groupLabel.setText(resourceMap.getString("groupLabel.text")); // NOI18N

                groupComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Group" }));
                groupComboBox.setName("groupComboBox"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(groupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kindOfContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(contactNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cellPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(groupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(kindOfContactText, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                                        .addGap(167, 167, 167))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(emailAdressText, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                                        .addContainerGap())
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cellPhoneNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                                        .addContainerGap())
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(contactNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                                        .addContainerGap())
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(addressText1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                                        .addContainerGap()))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(contactNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(contactNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cellPhoneNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cellPhoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(emailAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailAdressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(adressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addressText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(kindOfContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kindOfContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(groupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(groupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(acceptBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );

                adressLabel.getAccessibleContext().setAccessibleName(resourceMap.getString("adressLabel.AccessibleContext.accessibleName")); // NOI18N
                kindOfContactLabel.getAccessibleContext().setAccessibleName(resourceMap.getString("adressLabel1.AccessibleContext.accessibleName")); // NOI18N

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
	    // TODO add your handling code here:
}//GEN-LAST:event_cancelBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEditContact().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private java.awt.Button acceptBtn;
        private java.awt.TextField addressText1;
        private java.awt.Label adressLabel;
        private java.awt.Button cancelBtn;
        private java.awt.Label cellPhoneNumberLabel;
        private java.awt.TextField cellPhoneNumberText;
        private java.awt.Label contactNameLabel;
        private java.awt.TextField contactNameText;
        private java.awt.Label emailAdressLabel;
        private java.awt.TextField emailAdressText;
        private javax.swing.JComboBox groupComboBox;
        private java.awt.Label groupLabel;
        private java.awt.Label kindOfContactLabel;
        private java.awt.TextField kindOfContactText;
        // End of variables declaration//GEN-END:variables

}
