/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * @Author: David Vargas, Thibault Saunier, Carlos Lagos D.
 *
 * Created on Sep 27, 2009, 8:18:19 PM
 */

package upla.caltel;

import com.google.gdata.client.calendar.CalendarService;
import com.google.gdata.client.contacts.ContactsService;

/**
 *
 * @author Saunier Thibault;
 */

public class conexionwindow extends javax.swing.JFrame {

    private CalTelApp app;
    /** Creates new form addEvent */
    public conexionwindow(CalTelApp _app) {
        this.app = _app;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                eventNameLabel = new java.awt.Label();
                mailTxt = new java.awt.TextField();
                timeLabel = new java.awt.Label();
                acceptBtn = new java.awt.Button();
                cancelBtn = new java.awt.Button();
                jLabel1 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                passwordTxt = new javax.swing.JPasswordField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setName("Form"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(conexionwindow.class);
                eventNameLabel.setFont(resourceMap.getFont("eventNameLabel.font")); // NOI18N
                eventNameLabel.setName("eventNameLabel"); // NOI18N
                eventNameLabel.setText(resourceMap.getString("eventNameLabel.text")); // NOI18N

                mailTxt.setFont(resourceMap.getFont("emailTxt.font")); // NOI18N
                mailTxt.setName("emailTxt"); // NOI18N
                mailTxt.setText(resourceMap.getString("emailTxt.text")); // NOI18N

                timeLabel.setFont(resourceMap.getFont("timeLabel.font")); // NOI18N
                timeLabel.setName("timeLabel"); // NOI18N
                timeLabel.setText(resourceMap.getString("timeLabel.text")); // NOI18N

                acceptBtn.setLabel(resourceMap.getString("Accept.label")); // NOI18N
                acceptBtn.setName("Accept"); // NOI18N
                acceptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                acceptBtnMouseClicked(evt);
                        }
                });

                cancelBtn.setLabel(resourceMap.getString("cancelBtn.label")); // NOI18N
                cancelBtn.setName("cancelBtn"); // NOI18N
                cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                cancelBtnMouseClicked(evt);
                        }
                });
                cancelBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelBtnActionPerformed(evt);
                        }
                });

                jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
                jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
                jLabel1.setName("jLabel1"); // NOI18N

                jSeparator1.setName("jSeparator1"); // NOI18N

                passwordTxt.setText(resourceMap.getString("passwordTxt.text")); // NOI18N
                passwordTxt.setName("passwordTxt"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(207, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(197, 197, 197))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(399, Short.MAX_VALUE)
                                .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(eventNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(passwordTxt)
                                        .addComponent(mailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                                .addGap(48, 48, 48))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(eventNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                eventNameLabel.getAccessibleContext().setAccessibleName(resourceMap.getString("eventNameLabel.AccessibleContext.accessibleName")); // NOI18N
                timeLabel.getAccessibleContext().setAccessibleName(resourceMap.getString("timeLabel.AccessibleContext.accessibleName")); // NOI18N

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) 
      {
      }

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) 
      {
      }

    private void acceptBtnMouseClicked(java.awt.event.MouseEvent evt) {
        boolean connected = true;
        String userName = this.mailTxt.getText();
        char[] password = this.passwordTxt.getPassword ();
        String psswd = new String (password); 
         try 
           {
             System.out.println ("Connecting...");
             this.app.getContactService().setUserCredentials (userName, psswd);
           }
         catch ( com.google.gdata.util.AuthenticationException exception) 
           {
             connected = false;
             System.out.println("com.google.gdata.util.AuthenticationException");
           }
         try 
           {
             this.app.getCalendarService().setUserCredentials (userName, psswd);
           }
         catch ( com.google.gdata.util.AuthenticationException exception) 
           {
             connected = false;
             System.out.println("com.google.gdata.util.AuthenticationException");
           }
         /*catch (java.io.IOException exception)*/
         /*{*/

         /*}*/
         if (connected == true)
           {
             CalTelCalendarHandling calTelCalendarHandling = new CalTelCalendarHandling ();
             calTelCalendarHandling.setCalendarGui (this.app.getCalTelView (), this.app.getCalendarService(), userName);

             CalTelContactHandling calTelContactHandling = new CalTelContactHandling ();
             calTelContactHandling.setContactGui (this.app.getContactService(), this.app.getCalTelView (), userName);
             this.app.setUsername (userName);
             this.hide();
           }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conexionwindow(null).setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private java.awt.Button acceptBtn;
        private java.awt.Button cancelBtn;
        private java.awt.Label eventNameLabel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JSeparator jSeparator1;
        private java.awt.TextField mailTxt;
        private javax.swing.JPasswordField passwordTxt;
        private java.awt.Label timeLabel;
        // End of variables declaration//GEN-END:variables

}
